swagger: 2.0
host: petstore.swagger.io
basePath: /v1
schemes:
  - http
paths:
  /pet/{name}:
    put:
      operationId: updatePet
      x-scala-package: pet
      parameters:
        - name: name
          in: path
          type: string
        - name: body
          in: body
          schema:
            $ref: "#!/definitions/Pet"
      responses:
        200:
          schema:
            $ref: "#!/definitions/Pet"
  /pets:
    post:
      operationId: createPet
      x-scala-package: pet
      parameters:
        - name: name
          in: formData
          type: string
        - name: status
          in: formData
          type: string
        - name: file
          in: formData
          type: file
      responses:
        200:
          schema:
            $ref: "#!/definitions/Pet"
definitions:
  Pet:
    type: object
    properties:
      name:
        type: string
      status:
        type: string
  SqlConditionEqualityType:
    type: string
    enum:
      - EQUAL
      - LESS_THAN_OR_EQUAL
      - GREATER_THAN_OR_EQUAL
      - LESS
      - GREATER
      - NOT_EQUAL

  SqlConditionType:
    type: string
    enum:
      - AND
      - OR
      - NOT
  SqlCondition:
    type: object
    description: Container for a single where clause
    properties:
      type:
        $ref: "#/components/schemas/SqlConditionType"
      conditions:
        type: array
        items:
          $ref: "#/components/schemas/SqlCondition"
      field_name:
        type: string
      equality:
        $ref: "#/components/schemas/SqlConditionEqualityType"
      field_value:
        type: object
      v6:
        type: string
      v7:
        type: string
      v8:
        type: string
      v9:
        type: string
      v10:
        type: string
      v11:
        type: string
      v12:
        type: string
      v13:
        type: string
      v14:
        type: string
      v15:
        type: string
      v16:
        type: string
      v17:
        type: string
      v18:
        type: string
      v19:
        type: string
      v20:
        type: string
      v21:
        type: string
      v22:
        type: string
      v23:
        type: string
