swagger: 2.0
host: petstore.swagger.io
basePath: /v1
schemes:
  - http
paths:
  /pet/{name}:
    put:
      operationId: updatePet
      x-scala-package: pet
      parameters:
        - name: name
          in: path
          type: string
        - name: body
          in: body
          schema:
            $ref: "#!/definitions/Pet"
      responses:
        200:
          schema:
            $ref: "#!/definitions/Pet"
  /pets:
    post:
      operationId: createPet
      x-scala-package: pet
      parameters:
        - name: name
          in: formData
          type: string
        - name: status
          in: formData
          type: string
        - name: file
          in: formData
          type: file
      responses:
        200:
          schema:
            $ref: "#!/definitions/Pet"
definitions:
  Pet:
    type: object
    properties:
      name:
        type: string
      status:
        type: string
