/*
 * This file was generated by guardrail (https://github.com/guardrail-dev/guardrail).
 * Modifications will be overwritten; instead edit the OpenAPI/Swagger spec file.
 */
package sell.fulfillment.definitions

import cats.syntax.either._
import io.circe._
import io.circe.syntax._
import cats.implicits._
import _root_.sell.fulfillment.Implicits._
case class AddEvidencePaymentDisputeResponse(evidenceId: Option[String] = None)
object AddEvidencePaymentDisputeResponse {
  implicit val encodeAddEvidencePaymentDisputeResponse: _root_.io.circe.Encoder.AsObject[AddEvidencePaymentDisputeResponse] = {
    val readOnlyKeys = _root_.scala.Predef.Set[_root_.scala.Predef.String]()
    _root_.io.circe.Encoder.AsObject.instance[AddEvidencePaymentDisputeResponse](a => _root_.io.circe.JsonObject.fromIterable(_root_.scala.Vector(("evidenceId", a.evidenceId.asJson)))).mapJsonObject(_.filterKeys(key => !(readOnlyKeys contains key)))
  }
  implicit val decodeAddEvidencePaymentDisputeResponse: _root_.io.circe.Decoder[AddEvidencePaymentDisputeResponse] = new _root_.io.circe.Decoder[AddEvidencePaymentDisputeResponse] { final def apply(c: _root_.io.circe.HCursor): _root_.io.circe.Decoder.Result[AddEvidencePaymentDisputeResponse] = for (v0 <- c.downField("evidenceId").as[Option[String]]) yield AddEvidencePaymentDisputeResponse(v0) }
}