/*
 * This file was generated by guardrail (https://github.com/guardrail-dev/guardrail).
 * Modifications will be overwritten; instead edit the OpenAPI/Swagger spec file.
 */
package sell.fulfillment.definitions

import cats.syntax.either._
import io.circe._
import io.circe.syntax._
import cats.implicits._
import _root_.sell.fulfillment.Implicits._
case class DisputeSummaryResponse(href: Option[String] = None, limit: Option[Int] = None, next: Option[String] = None, offset: Option[Int] = None, paymentDisputeSummaries: Option[_root_.scala.Vector[PaymentDisputeSummary]] = None, prev: Option[String] = None, total: Option[Int] = None)
object DisputeSummaryResponse {
  implicit val encodeDisputeSummaryResponse: _root_.io.circe.Encoder.AsObject[DisputeSummaryResponse] = {
    val readOnlyKeys = _root_.scala.Predef.Set[_root_.scala.Predef.String]()
    _root_.io.circe.Encoder.AsObject.instance[DisputeSummaryResponse](a => _root_.io.circe.JsonObject.fromIterable(_root_.scala.Vector(("href", a.href.asJson), ("limit", a.limit.asJson), ("next", a.next.asJson), ("offset", a.offset.asJson), ("paymentDisputeSummaries", a.paymentDisputeSummaries.asJson), ("prev", a.prev.asJson), ("total", a.total.asJson)))).mapJsonObject(_.filterKeys(key => !(readOnlyKeys contains key)))
  }
  implicit val decodeDisputeSummaryResponse: _root_.io.circe.Decoder[DisputeSummaryResponse] = new _root_.io.circe.Decoder[DisputeSummaryResponse] { final def apply(c: _root_.io.circe.HCursor): _root_.io.circe.Decoder.Result[DisputeSummaryResponse] = for (v0 <- c.downField("href").as[Option[String]]; v1 <- c.downField("limit").as[Option[Int]]; v2 <- c.downField("next").as[Option[String]]; v3 <- c.downField("offset").as[Option[Int]]; v4 <- c.downField("paymentDisputeSummaries").as[Option[_root_.scala.Vector[PaymentDisputeSummary]]]; v5 <- c.downField("prev").as[Option[String]]; v6 <- c.downField("total").as[Option[Int]]) yield DisputeSummaryResponse(v0, v1, v2, v3, v4, v5, v6) }
}