/*
 * This file was generated by guardrail (https://github.com/guardrail-dev/guardrail).
 * Modifications will be overwritten; instead edit the OpenAPI/Swagger spec file.
 */
package sell.fulfillment.definitions

import cats.syntax.either._
import io.circe._
import io.circe.syntax._
import cats.implicits._
import _root_.sell.fulfillment.Implicits._
case class EbayTaxReference(name: Option[String] = None, value: Option[String] = None)
object EbayTaxReference {
  implicit val encodeEbayTaxReference: _root_.io.circe.Encoder.AsObject[EbayTaxReference] = {
    val readOnlyKeys = _root_.scala.Predef.Set[_root_.scala.Predef.String]()
    _root_.io.circe.Encoder.AsObject.instance[EbayTaxReference](a => _root_.io.circe.JsonObject.fromIterable(_root_.scala.Vector(("name", a.name.asJson), ("value", a.value.asJson)))).mapJsonObject(_.filterKeys(key => !(readOnlyKeys contains key)))
  }
  implicit val decodeEbayTaxReference: _root_.io.circe.Decoder[EbayTaxReference] = new _root_.io.circe.Decoder[EbayTaxReference] { final def apply(c: _root_.io.circe.HCursor): _root_.io.circe.Decoder.Result[EbayTaxReference] = for (v0 <- c.downField("name").as[Option[String]]; v1 <- c.downField("value").as[Option[String]]) yield EbayTaxReference(v0, v1) }
}