/*
 * This file was generated by guardrail (https://github.com/guardrail-dev/guardrail).
 * Modifications will be overwritten; instead edit the OpenAPI/Swagger spec file.
 */
package sell.fulfillment.definitions

import cats.syntax.either._
import io.circe._
import io.circe.syntax._
import cats.implicits._
import _root_.sell.fulfillment.Implicits._
case class EbayCollectAndRemitTax(amount: Option[Amount] = None, ebayReference: Option[EbayTaxReference] = None, taxType: Option[String] = None, collectionMethod: Option[String] = None)
object EbayCollectAndRemitTax {
  implicit val encodeEbayCollectAndRemitTax: _root_.io.circe.Encoder.AsObject[EbayCollectAndRemitTax] = {
    val readOnlyKeys = _root_.scala.Predef.Set[_root_.scala.Predef.String]()
    _root_.io.circe.Encoder.AsObject.instance[EbayCollectAndRemitTax](a => _root_.io.circe.JsonObject.fromIterable(_root_.scala.Vector(("amount", a.amount.asJson), ("ebayReference", a.ebayReference.asJson), ("taxType", a.taxType.asJson), ("collectionMethod", a.collectionMethod.asJson)))).mapJsonObject(_.filterKeys(key => !(readOnlyKeys contains key)))
  }
  implicit val decodeEbayCollectAndRemitTax: _root_.io.circe.Decoder[EbayCollectAndRemitTax] = new _root_.io.circe.Decoder[EbayCollectAndRemitTax] { final def apply(c: _root_.io.circe.HCursor): _root_.io.circe.Decoder.Result[EbayCollectAndRemitTax] = for (v0 <- c.downField("amount").as[Option[Amount]]; v1 <- c.downField("ebayReference").as[Option[EbayTaxReference]]; v2 <- c.downField("taxType").as[Option[String]]; v3 <- c.downField("collectionMethod").as[Option[String]]) yield EbayCollectAndRemitTax(v0, v1, v2, v3) }
}