/*
 * This file was generated by guardrail (https://github.com/guardrail-dev/guardrail).
 * Modifications will be overwritten; instead edit the OpenAPI/Swagger spec file.
 */
package sell.fulfillment.definitions

import cats.syntax.either._
import io.circe._
import io.circe.syntax._
import cats.implicits._
import _root_.sell.fulfillment.Implicits._
case class ErrorParameter(name: Option[String] = None, value: Option[String] = None)
object ErrorParameter {
  implicit val encodeErrorParameter: _root_.io.circe.Encoder.AsObject[ErrorParameter] = {
    val readOnlyKeys = _root_.scala.Predef.Set[_root_.scala.Predef.String]()
    _root_.io.circe.Encoder.AsObject.instance[ErrorParameter](a => _root_.io.circe.JsonObject.fromIterable(_root_.scala.Vector(("name", a.name.asJson), ("value", a.value.asJson)))).mapJsonObject(_.filterKeys(key => !(readOnlyKeys contains key)))
  }
  implicit val decodeErrorParameter: _root_.io.circe.Decoder[ErrorParameter] = new _root_.io.circe.Decoder[ErrorParameter] { final def apply(c: _root_.io.circe.HCursor): _root_.io.circe.Decoder.Result[ErrorParameter] = for (v0 <- c.downField("name").as[Option[String]]; v1 <- c.downField("value").as[Option[String]]) yield ErrorParameter(v0, v1) }
}