/*
 * This file was generated by guardrail (https://github.com/guardrail-dev/guardrail).
 * Modifications will be overwritten; instead edit the OpenAPI/Swagger spec file.
 */
package sell.fulfillment.definitions

import cats.syntax.either._
import io.circe._
import io.circe.syntax._
import cats.implicits._
import _root_.sell.fulfillment.Implicits._
case class EvidenceRequest(evidenceId: Option[String] = None, evidenceType: Option[String] = None, lineItems: Option[_root_.scala.Vector[OrderLineItems]] = None, requestDate: Option[String] = None, respondByDate: Option[String] = None)
object EvidenceRequest {
  implicit val encodeEvidenceRequest: _root_.io.circe.Encoder.AsObject[EvidenceRequest] = {
    val readOnlyKeys = _root_.scala.Predef.Set[_root_.scala.Predef.String]()
    _root_.io.circe.Encoder.AsObject.instance[EvidenceRequest](a => _root_.io.circe.JsonObject.fromIterable(_root_.scala.Vector(("evidenceId", a.evidenceId.asJson), ("evidenceType", a.evidenceType.asJson), ("lineItems", a.lineItems.asJson), ("requestDate", a.requestDate.asJson), ("respondByDate", a.respondByDate.asJson)))).mapJsonObject(_.filterKeys(key => !(readOnlyKeys contains key)))
  }
  implicit val decodeEvidenceRequest: _root_.io.circe.Decoder[EvidenceRequest] = new _root_.io.circe.Decoder[EvidenceRequest] { final def apply(c: _root_.io.circe.HCursor): _root_.io.circe.Decoder.Result[EvidenceRequest] = for (v0 <- c.downField("evidenceId").as[Option[String]]; v1 <- c.downField("evidenceType").as[Option[String]]; v2 <- c.downField("lineItems").as[Option[_root_.scala.Vector[OrderLineItems]]]; v3 <- c.downField("requestDate").as[Option[String]]; v4 <- c.downField("respondByDate").as[Option[String]]) yield EvidenceRequest(v0, v1, v2, v3, v4) }
}