/*
 * This file was generated by guardrail (https://github.com/guardrail-dev/guardrail).
 * Modifications will be overwritten; instead edit the OpenAPI/Swagger spec file.
 */
package sell.fulfillment.definitions

import cats.syntax.either._
import io.circe._
import io.circe.syntax._
import cats.implicits._
import _root_.sell.fulfillment.Implicits._
case class FileEvidence(fileId: Option[String] = None)
object FileEvidence {
  implicit val encodeFileEvidence: _root_.io.circe.Encoder.AsObject[FileEvidence] = {
    val readOnlyKeys = _root_.scala.Predef.Set[_root_.scala.Predef.String]()
    _root_.io.circe.Encoder.AsObject.instance[FileEvidence](a => _root_.io.circe.JsonObject.fromIterable(_root_.scala.Vector(("fileId", a.fileId.asJson)))).mapJsonObject(_.filterKeys(key => !(readOnlyKeys contains key)))
  }
  implicit val decodeFileEvidence: _root_.io.circe.Decoder[FileEvidence] = new _root_.io.circe.Decoder[FileEvidence] { final def apply(c: _root_.io.circe.HCursor): _root_.io.circe.Decoder.Result[FileEvidence] = for (v0 <- c.downField("fileId").as[Option[String]]) yield FileEvidence(v0) }
}