/*
 * This file was generated by guardrail (https://github.com/guardrail-dev/guardrail).
 * Modifications will be overwritten; instead edit the OpenAPI/Swagger spec file.
 */
package sell.fulfillment.definitions

import cats.syntax.either._
import io.circe._
import io.circe.syntax._
import cats.implicits._
import _root_.sell.fulfillment.Implicits._
case class GiftDetails(message: Option[String] = None, recipientEmail: Option[String] = None, senderName: Option[String] = None)
object GiftDetails {
  implicit val encodeGiftDetails: _root_.io.circe.Encoder.AsObject[GiftDetails] = {
    val readOnlyKeys = _root_.scala.Predef.Set[_root_.scala.Predef.String]()
    _root_.io.circe.Encoder.AsObject.instance[GiftDetails](a => _root_.io.circe.JsonObject.fromIterable(_root_.scala.Vector(("message", a.message.asJson), ("recipientEmail", a.recipientEmail.asJson), ("senderName", a.senderName.asJson)))).mapJsonObject(_.filterKeys(key => !(readOnlyKeys contains key)))
  }
  implicit val decodeGiftDetails: _root_.io.circe.Decoder[GiftDetails] = new _root_.io.circe.Decoder[GiftDetails] { final def apply(c: _root_.io.circe.HCursor): _root_.io.circe.Decoder.Result[GiftDetails] = for (v0 <- c.downField("message").as[Option[String]]; v1 <- c.downField("recipientEmail").as[Option[String]]; v2 <- c.downField("senderName").as[Option[String]]) yield GiftDetails(v0, v1, v2) }
}