/*
 * This file was generated by guardrail (https://github.com/guardrail-dev/guardrail).
 * Modifications will be overwritten; instead edit the OpenAPI/Swagger spec file.
 */
package sell.fulfillment.definitions

import cats.syntax.either._
import io.circe._
import io.circe.syntax._
import cats.implicits._
import _root_.sell.fulfillment.Implicits._
case class LegacyReference(legacyItemId: Option[String] = None, legacyTransactionId: Option[String] = None)
object LegacyReference {
  implicit val encodeLegacyReference: _root_.io.circe.Encoder.AsObject[LegacyReference] = {
    val readOnlyKeys = _root_.scala.Predef.Set[_root_.scala.Predef.String]()
    _root_.io.circe.Encoder.AsObject.instance[LegacyReference](a => _root_.io.circe.JsonObject.fromIterable(_root_.scala.Vector(("legacyItemId", a.legacyItemId.asJson), ("legacyTransactionId", a.legacyTransactionId.asJson)))).mapJsonObject(_.filterKeys(key => !(readOnlyKeys contains key)))
  }
  implicit val decodeLegacyReference: _root_.io.circe.Decoder[LegacyReference] = new _root_.io.circe.Decoder[LegacyReference] { final def apply(c: _root_.io.circe.HCursor): _root_.io.circe.Decoder.Result[LegacyReference] = for (v0 <- c.downField("legacyItemId").as[Option[String]]; v1 <- c.downField("legacyTransactionId").as[Option[String]]) yield LegacyReference(v0, v1) }
}