/*
 * This file was generated by guardrail (https://github.com/guardrail-dev/guardrail).
 * Modifications will be overwritten; instead edit the OpenAPI/Swagger spec file.
 */
package sell.fulfillment.definitions

import cats.syntax.either._
import io.circe._
import io.circe.syntax._
import cats.implicits._
import _root_.sell.fulfillment.Implicits._
case class LineItemReference(lineItemId: Option[String] = None, quantity: Option[Int] = None)
object LineItemReference {
  implicit val encodeLineItemReference: _root_.io.circe.Encoder.AsObject[LineItemReference] = {
    val readOnlyKeys = _root_.scala.Predef.Set[_root_.scala.Predef.String]()
    _root_.io.circe.Encoder.AsObject.instance[LineItemReference](a => _root_.io.circe.JsonObject.fromIterable(_root_.scala.Vector(("lineItemId", a.lineItemId.asJson), ("quantity", a.quantity.asJson)))).mapJsonObject(_.filterKeys(key => !(readOnlyKeys contains key)))
  }
  implicit val decodeLineItemReference: _root_.io.circe.Decoder[LineItemReference] = new _root_.io.circe.Decoder[LineItemReference] { final def apply(c: _root_.io.circe.HCursor): _root_.io.circe.Decoder.Result[LineItemReference] = for (v0 <- c.downField("lineItemId").as[Option[String]]; v1 <- c.downField("quantity").as[Option[Int]]) yield LineItemReference(v0, v1) }
}