/*
 * This file was generated by guardrail (https://github.com/guardrail-dev/guardrail).
 * Modifications will be overwritten; instead edit the OpenAPI/Swagger spec file.
 */
package sell.fulfillment.definitions

import cats.syntax.either._
import io.circe._
import io.circe.syntax._
import cats.implicits._
import _root_.sell.fulfillment.Implicits._
case class OrderLineItems(itemId: Option[String] = None, lineItemId: Option[String] = None)
object OrderLineItems {
  implicit val encodeOrderLineItems: _root_.io.circe.Encoder.AsObject[OrderLineItems] = {
    val readOnlyKeys = _root_.scala.Predef.Set[_root_.scala.Predef.String]()
    _root_.io.circe.Encoder.AsObject.instance[OrderLineItems](a => _root_.io.circe.JsonObject.fromIterable(_root_.scala.Vector(("itemId", a.itemId.asJson), ("lineItemId", a.lineItemId.asJson)))).mapJsonObject(_.filterKeys(key => !(readOnlyKeys contains key)))
  }
  implicit val decodeOrderLineItems: _root_.io.circe.Decoder[OrderLineItems] = new _root_.io.circe.Decoder[OrderLineItems] { final def apply(c: _root_.io.circe.HCursor): _root_.io.circe.Decoder.Result[OrderLineItems] = for (v0 <- c.downField("itemId").as[Option[String]]; v1 <- c.downField("lineItemId").as[Option[String]]) yield OrderLineItems(v0, v1) }
}