/*
 * This file was generated by guardrail (https://github.com/guardrail-dev/guardrail).
 * Modifications will be overwritten; instead edit the OpenAPI/Swagger spec file.
 */
package sell.fulfillment.definitions

import cats.syntax.either._
import io.circe._
import io.circe.syntax._
import cats.implicits._
import _root_.sell.fulfillment.Implicits._
case class PhoneNumber(phoneNumber: Option[String] = None)
object PhoneNumber {
  implicit val encodePhoneNumber: _root_.io.circe.Encoder.AsObject[PhoneNumber] = {
    val readOnlyKeys = _root_.scala.Predef.Set[_root_.scala.Predef.String]()
    _root_.io.circe.Encoder.AsObject.instance[PhoneNumber](a => _root_.io.circe.JsonObject.fromIterable(_root_.scala.Vector(("phoneNumber", a.phoneNumber.asJson)))).mapJsonObject(_.filterKeys(key => !(readOnlyKeys contains key)))
  }
  implicit val decodePhoneNumber: _root_.io.circe.Decoder[PhoneNumber] = new _root_.io.circe.Decoder[PhoneNumber] { final def apply(c: _root_.io.circe.HCursor): _root_.io.circe.Decoder.Result[PhoneNumber] = for (v0 <- c.downField("phoneNumber").as[Option[String]]) yield PhoneNumber(v0) }
}