/*
 * This file was generated by guardrail (https://github.com/guardrail-dev/guardrail).
 * Modifications will be overwritten; instead edit the OpenAPI/Swagger spec file.
 */
package sell.fulfillment.definitions

import cats.syntax.either._
import io.circe._
import io.circe.syntax._
import cats.implicits._
import _root_.sell.fulfillment.Implicits._
case class PickupStep(merchantLocationKey: Option[String] = None)
object PickupStep {
  implicit val encodePickupStep: _root_.io.circe.Encoder.AsObject[PickupStep] = {
    val readOnlyKeys = _root_.scala.Predef.Set[_root_.scala.Predef.String]()
    _root_.io.circe.Encoder.AsObject.instance[PickupStep](a => _root_.io.circe.JsonObject.fromIterable(_root_.scala.Vector(("merchantLocationKey", a.merchantLocationKey.asJson)))).mapJsonObject(_.filterKeys(key => !(readOnlyKeys contains key)))
  }
  implicit val decodePickupStep: _root_.io.circe.Decoder[PickupStep] = new _root_.io.circe.Decoder[PickupStep] { final def apply(c: _root_.io.circe.HCursor): _root_.io.circe.Decoder.Result[PickupStep] = for (v0 <- c.downField("merchantLocationKey").as[Option[String]]) yield PickupStep(v0) }
}