/*
 * This file was generated by guardrail (https://github.com/guardrail-dev/guardrail).
 * Modifications will be overwritten; instead edit the OpenAPI/Swagger spec file.
 */
package sell.fulfillment.definitions

import cats.syntax.either._
import io.circe._
import io.circe.syntax._
import cats.implicits._
import _root_.sell.fulfillment.Implicits._
case class PostSaleAuthenticationProgram(outcomeReason: Option[String] = None, status: Option[String] = None)
object PostSaleAuthenticationProgram {
  implicit val encodePostSaleAuthenticationProgram: _root_.io.circe.Encoder.AsObject[PostSaleAuthenticationProgram] = {
    val readOnlyKeys = _root_.scala.Predef.Set[_root_.scala.Predef.String]()
    _root_.io.circe.Encoder.AsObject.instance[PostSaleAuthenticationProgram](a => _root_.io.circe.JsonObject.fromIterable(_root_.scala.Vector(("outcomeReason", a.outcomeReason.asJson), ("status", a.status.asJson)))).mapJsonObject(_.filterKeys(key => !(readOnlyKeys contains key)))
  }
  implicit val decodePostSaleAuthenticationProgram: _root_.io.circe.Decoder[PostSaleAuthenticationProgram] = new _root_.io.circe.Decoder[PostSaleAuthenticationProgram] { final def apply(c: _root_.io.circe.HCursor): _root_.io.circe.Decoder.Result[PostSaleAuthenticationProgram] = for (v0 <- c.downField("outcomeReason").as[Option[String]]; v1 <- c.downField("status").as[Option[String]]) yield PostSaleAuthenticationProgram(v0, v1) }
}