/*
 * This file was generated by guardrail (https://github.com/guardrail-dev/guardrail).
 * Modifications will be overwritten; instead edit the OpenAPI/Swagger spec file.
 */
package sell.fulfillment.definitions

import cats.syntax.either._
import io.circe._
import io.circe.syntax._
import cats.implicits._
import _root_.sell.fulfillment.Implicits._
case class RefundItem(refundAmount: Option[SimpleAmount] = None, lineItemId: Option[String] = None, legacyReference: Option[LegacyReference] = None)
object RefundItem {
  implicit val encodeRefundItem: _root_.io.circe.Encoder.AsObject[RefundItem] = {
    val readOnlyKeys = _root_.scala.Predef.Set[_root_.scala.Predef.String]()
    _root_.io.circe.Encoder.AsObject.instance[RefundItem](a => _root_.io.circe.JsonObject.fromIterable(_root_.scala.Vector(("refundAmount", a.refundAmount.asJson), ("lineItemId", a.lineItemId.asJson), ("legacyReference", a.legacyReference.asJson)))).mapJsonObject(_.filterKeys(key => !(readOnlyKeys contains key)))
  }
  implicit val decodeRefundItem: _root_.io.circe.Decoder[RefundItem] = new _root_.io.circe.Decoder[RefundItem] { final def apply(c: _root_.io.circe.HCursor): _root_.io.circe.Decoder.Result[RefundItem] = for (v0 <- c.downField("refundAmount").as[Option[SimpleAmount]]; v1 <- c.downField("lineItemId").as[Option[String]]; v2 <- c.downField("legacyReference").as[Option[LegacyReference]]) yield RefundItem(v0, v1, v2) }
}