/*
 * This file was generated by guardrail (https://github.com/guardrail-dev/guardrail).
 * Modifications will be overwritten; instead edit the OpenAPI/Swagger spec file.
 */
package sell.fulfillment.definitions

import cats.syntax.either._
import io.circe._
import io.circe.syntax._
import cats.implicits._
import _root_.sell.fulfillment.Implicits._
case class SellerActionsToRelease(sellerActionToRelease: Option[String] = None)
object SellerActionsToRelease {
  implicit val encodeSellerActionsToRelease: _root_.io.circe.Encoder.AsObject[SellerActionsToRelease] = {
    val readOnlyKeys = _root_.scala.Predef.Set[_root_.scala.Predef.String]()
    _root_.io.circe.Encoder.AsObject.instance[SellerActionsToRelease](a => _root_.io.circe.JsonObject.fromIterable(_root_.scala.Vector(("sellerActionToRelease", a.sellerActionToRelease.asJson)))).mapJsonObject(_.filterKeys(key => !(readOnlyKeys contains key)))
  }
  implicit val decodeSellerActionsToRelease: _root_.io.circe.Decoder[SellerActionsToRelease] = new _root_.io.circe.Decoder[SellerActionsToRelease] { final def apply(c: _root_.io.circe.HCursor): _root_.io.circe.Decoder.Result[SellerActionsToRelease] = for (v0 <- c.downField("sellerActionToRelease").as[Option[String]]) yield SellerActionsToRelease(v0) }
}