/*
 * This file was generated by guardrail (https://github.com/guardrail-dev/guardrail).
 * Modifications will be overwritten; instead edit the OpenAPI/Swagger spec file.
 */
package sell.fulfillment.definitions

import cats.syntax.either._
import io.circe._
import io.circe.syntax._
import cats.implicits._
import _root_.sell.fulfillment.Implicits._
case class SimpleAmount(currency: Option[String] = None, value: Option[String] = None)
object SimpleAmount {
  implicit val encodeSimpleAmount: _root_.io.circe.Encoder.AsObject[SimpleAmount] = {
    val readOnlyKeys = _root_.scala.Predef.Set[_root_.scala.Predef.String]()
    _root_.io.circe.Encoder.AsObject.instance[SimpleAmount](a => _root_.io.circe.JsonObject.fromIterable(_root_.scala.Vector(("currency", a.currency.asJson), ("value", a.value.asJson)))).mapJsonObject(_.filterKeys(key => !(readOnlyKeys contains key)))
  }
  implicit val decodeSimpleAmount: _root_.io.circe.Decoder[SimpleAmount] = new _root_.io.circe.Decoder[SimpleAmount] { final def apply(c: _root_.io.circe.HCursor): _root_.io.circe.Decoder.Result[SimpleAmount] = for (v0 <- c.downField("currency").as[Option[String]]; v1 <- c.downField("value").as[Option[String]]) yield SimpleAmount(v0, v1) }
}