/*
 * This file was generated by guardrail (https://github.com/guardrail-dev/guardrail).
 * Modifications will be overwritten; instead edit the OpenAPI/Swagger spec file.
 */
package sell.fulfillment.definitions

import cats.syntax.either._
import io.circe._
import io.circe.syntax._
import cats.implicits._
import _root_.sell.fulfillment.Implicits._
case class TaxIdentifier(taxpayerId: Option[String] = None, taxIdentifierType: Option[String] = None, issuingCountry: Option[String] = None)
object TaxIdentifier {
  implicit val encodeTaxIdentifier: _root_.io.circe.Encoder.AsObject[TaxIdentifier] = {
    val readOnlyKeys = _root_.scala.Predef.Set[_root_.scala.Predef.String]()
    _root_.io.circe.Encoder.AsObject.instance[TaxIdentifier](a => _root_.io.circe.JsonObject.fromIterable(_root_.scala.Vector(("taxpayerId", a.taxpayerId.asJson), ("taxIdentifierType", a.taxIdentifierType.asJson), ("issuingCountry", a.issuingCountry.asJson)))).mapJsonObject(_.filterKeys(key => !(readOnlyKeys contains key)))
  }
  implicit val decodeTaxIdentifier: _root_.io.circe.Decoder[TaxIdentifier] = new _root_.io.circe.Decoder[TaxIdentifier] { final def apply(c: _root_.io.circe.HCursor): _root_.io.circe.Decoder.Result[TaxIdentifier] = for (v0 <- c.downField("taxpayerId").as[Option[String]]; v1 <- c.downField("taxIdentifierType").as[Option[String]]; v2 <- c.downField("issuingCountry").as[Option[String]]) yield TaxIdentifier(v0, v1, v2) }
}