/*
 * This file was generated by guardrail (https://github.com/guardrail-dev/guardrail).
 * Modifications will be overwritten; instead edit the OpenAPI/Swagger spec file.
 */
package sell.fulfillment.definitions

import cats.syntax.either._
import io.circe._
import io.circe.syntax._
import cats.implicits._
import _root_.sell.fulfillment.Implicits._
case class UpdateEvidencePaymentDisputeRequest(evidenceId: Option[String] = None, evidenceType: Option[String] = None, files: Option[_root_.scala.Vector[FileEvidence]] = None, lineItems: Option[_root_.scala.Vector[OrderLineItems]] = None)
object UpdateEvidencePaymentDisputeRequest {
  implicit val encodeUpdateEvidencePaymentDisputeRequest: _root_.io.circe.Encoder.AsObject[UpdateEvidencePaymentDisputeRequest] = {
    val readOnlyKeys = _root_.scala.Predef.Set[_root_.scala.Predef.String]()
    _root_.io.circe.Encoder.AsObject.instance[UpdateEvidencePaymentDisputeRequest](a => _root_.io.circe.JsonObject.fromIterable(_root_.scala.Vector(("evidenceId", a.evidenceId.asJson), ("evidenceType", a.evidenceType.asJson), ("files", a.files.asJson), ("lineItems", a.lineItems.asJson)))).mapJsonObject(_.filterKeys(key => !(readOnlyKeys contains key)))
  }
  implicit val decodeUpdateEvidencePaymentDisputeRequest: _root_.io.circe.Decoder[UpdateEvidencePaymentDisputeRequest] = new _root_.io.circe.Decoder[UpdateEvidencePaymentDisputeRequest] { final def apply(c: _root_.io.circe.HCursor): _root_.io.circe.Decoder.Result[UpdateEvidencePaymentDisputeRequest] = for (v0 <- c.downField("evidenceId").as[Option[String]]; v1 <- c.downField("evidenceType").as[Option[String]]; v2 <- c.downField("files").as[Option[_root_.scala.Vector[FileEvidence]]]; v3 <- c.downField("lineItems").as[Option[_root_.scala.Vector[OrderLineItems]]]) yield UpdateEvidencePaymentDisputeRequest(v0, v1, v2, v3) }
}